name: projetopokedex
description: "Pokemon pokedex flutter"
publish_to: 'none' 

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_launcher_icons: ^0.14.4
  isar_community: ^3.2.0-dev.2
  isar_community_flutter_libs: ^3.2.0-dev.2
  path_provider: ^2.1.5
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_community_generator: ^3.3.2

flutter: 
  uses-material-design: true

 